### ISSUE TITLE
support this library for desktop?

### ISSUE THREAD

**Issue by MostFull** [m-r-davari/flutter_3d_controller#1]
Hi
Is it possible to support this library for Desktop?
Like Windows

**Comment by m-r-davari** [comment]
Hi,
For now it just support Android,iOS and Web, but i will add Desktop support later.

**Comment by MostFull** [comment]
Thank you, I hope it will be done for the desktop as soon as possible

في الجمعة، ٥ يناير ٢٠٢٤, ٢:٢٥ م MohammadReza Davari <
***@***.***> كتب:
