### ISSUE TITLE
Unable to fetch Animations and textures on iOS.

### ISSUE THREAD

**Issue by KamathVishak96** [m-r-davari/flutter_3d_controller#12]
After the model is loaded, I am calling the controller.getAvailableTextures() and controller.getAvailableAnimations(). This works on Android and it returns the list of Textures and Animations. But on iOS, I don't get any response, instead see this printed on the console - `Return type of evaluateJavaScript is not directly supported: __NSArrayM. Returned description of value.` Also the code terminates there and doesn't go further. There is no crash though, but the execution just stops their.

Flutter doctor -v

[!] Flutter (Channel stable, 3.19.2, on macOS 13.6.4 22G513 darwin-arm64, locale en-IN)
    • Flutter version 3.19.2 on channel stable at /Users/vishakakamath/development/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/vishakakamath/development/flutter. Consider adding
      /Users/vishakakamath/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (3 months ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/vishakakamath/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

**Comment by m-r-davari** [comment]
Fixed on version **1.3.1** ✅
