### ISSUE TITLE
Loading animations from a separate file

### ISSUE THREAD

**Issue by sdivakarrajesh** [m-r-davari/flutter_3d_controller#14]
I have a glb model for a character and their animations in a separate gltf and glb file. How can i load them and apply the animation on the main character?

**Comment by m-r-davari** [comment]
you must use 3D model with embedded animations, its easy to use just check the example or ReadMe file to see how to use it.

**Comment by danieljiwonkang98** [comment]
@m-r-davari  Hello I am new to using glb files. I have glb files for the animations and a glb model for a character. I don't quite understand what you meant by that we have to use 3D model with embedded animations. How do you make embedded animations, do we have to use rendering software to create those?

**Comment by m-r-davari** [comment]
Hi

Glb and gltf are the 3d models format that can hold coordinates of moving
rigged models that we now it as animation,
In other words glb and gltf could hold animation data and 3d model data in
both at the same time in themselves.

So if you have one 3d model for your character and other 3d models for its
animation you can’t use this package or any other package for your use case,
You must create one simple 3d model that contains 3d character itselft and
its animation data, exactly like 3d model of package example(business man)

And for creating such glb or gltf 3d file, you might need to use 3d
softwares like blender or 3dMax

I hope this description could help you


*“If you want something you've never had...You must do something you've
never done.” *

**Comment by danieljiwonkang98** [comment]
@m-r-davari Awesome Thank You! Will check out.
