### ISSUE TITLE
Fetaure like DecalGemoetry of three.js

### ISSUE THREAD

**Issue by vraj129** [m-r-davari/flutter_3d_controller#17]
This is not an issue but wanted to know if this feature gives a capability like three.js [DecalGeometry](https://threejs.org/docs/#examples/en/geometries/DecalGeometry) where in we can customize each mesh of the glb model

**Comment by m-r-davari** [comment]
Very good Idea, Maybe we can add three.js in our package to support this kind of features.
Currently the core of this package is modelViewer and I'm not sure it can support feature like that.
If you can make improvements and add this feature to package, please do not hesitate to make PR.
