### ISSUE TITLE
[Question] Is it possible to change textures in multiple objects within one model?

### ISSUE THREAD

**Issue by yokawaiik** [m-r-davari/flutter_3d_controller#20]
Hello!

I saw that in this library you can change textures on models.

Is it possible to change textures for different objects within the same model?

Using the example of a house in which the component parts may have different textures:
1. Windows
2. Doors
3. Sheathing
4. Roof

**Comment by shegal** [comment]
It is possible. Just setup separate gltf texture slots for different objects (I managed to do this in blender)

**Comment by m-r-davari** [comment]
Hi, sorry for late reply.
Yes Exactly, It is possible to change texture of objects and it will need multiple embedded texture/variant of your .gltf model, and it can be done by 3D design software like Blender
