### ISSUE TITLE
unable to load .obj format 

### ISSUE THREAD

**Issue by dhanashrih00** [m-r-davari/flutter_3d_controller#21]
![Screenshot from 2024-07-30 16-31-53](https://github.com/user-attachments/assets/08eca67f-52e6-4e47-beba-8266cdbd6b39)

**Comment by lualbertovargas** [comment]
yes Bro not found , try changing the format to glb

**Comment by m-r-davari** [comment]
I have fixed .obj loading problem, will release on v2.0.0

**Comment by m-r-davari** [comment]
Feature has been added in v2.0.0 ✅

`Flutter3DViewer.obj(
                src: 'assets/flutter_dash.obj', ... )`
