### ISSUE TITLE
In flutter web, glb file work in local but not on server

### ISSUE THREAD

**Issue by GoudarzJ** [m-r-davari/flutter_3d_controller#24]
Hi,
First of all thank you for your great pacage.
In flutter web I load a gb file from asset in it works perfectly in local but when I run it from debian server. glb file will load but nothing will shows.

Please guide me

**Comment by Korea19800** [comment]
Can you show your main.dart code?

**Comment by m-r-davari** [comment]
Hi,
Could you please provide more info, because loading models from url will work fine on web as the url sample that existed on example,
can your server provide download link without cross origin error?
