### ISSUE TITLE
Why can’t it rotate 360 ​​degrees?

### ISSUE THREAD

**Issue by bluemoon-i** [m-r-davari/flutter_3d_controller#25]
Why can’t it rotate 360 ​​degrees?

**Comment by m-r-davari** [comment]
what do you mean, because it works fine, can you give more info?

**Comment by bluemoon-i** [comment]
How do I flip the model 360 degrees up and down

**Comment by bluemoon-i** [comment]
like this: https://3dmol.csb.pitt.edu/doc/index.html

**Comment by bluemoon-i** [comment]
https://github.com/google/model-viewer/issues/3363

**Comment by m-r-davari** [comment]
sorry flipping the model is not possible right now, but you can do rotating by package
