### ISSUE TITLE
Disable click inside viewer

### ISSUE THREAD

**Issue by Jouca** [m-r-davari/flutter_3d_controller#27]
Hello!
I've noticed that your package would be pretty interesting for my project to control 3D models inside my Android app.

However, I've noticed that the controller inside the 3D viewer is impossible to disable (what I mean is that you can't disable clicking without removing the controller), I wanted to know if it's possible to make that the click could be disabled on the viewer but you can still control it dynamically from methods?

**Comment by m-r-davari** [comment]
Hi,
You mean you wanna disable touch but still control it via controller in code right?

**Comment by Jouca** [comment]
Hello,
Yea, that's exactly what I meant, it would be cool to control it on the code and have the option to disable touch

**Comment by m-r-davari** [comment]
I will add it next version, thanks for supporting me to upgrade my package

**Comment by m-r-davari** [comment]
Feature has been added in v2.0.0 ✅
[check ](https://pub.dev/packages/flutter_3d_controller)
