### ISSUE TITLE
How to play two animations together

### ISSUE THREAD

**Issue by worldwidee** [m-r-davari/flutter_3d_controller#28]
I have two animations, Idle and speaking. I want to play these two together. Usually all 3d packages in flutter allow single animation. Is it not normally possible to play two animations together?

**Comment by m-r-davari** [comment]
its not possible in none of 3d model in none of platform or packages, for your approach you need to design new animation which includes both idle and talk effect.

**Comment by worldwidee** [comment]
https://gltf-viewer.donmccurdy.com/
No, of course it's possible. If it wasn't possible, we wouldn't be able to make what we call "games". You can try and see for yourself on this site. It is possible to do this with the ThreeJs package in javascript. I wanted to ask because scene lighting, camera settings etc. are easier in flutter packages. But I see that this is not possible in these packages. All flutter packages already do it via webview with javascript. So this can be done.
