### ISSUE TITLE
is it possible to add decorations?

### ISSUE THREAD

**Issue by illusionGeorge** [m-r-davari/flutter_3d_controller#3]
ls it possible ike 3d avatar to let model change clothes hair or glasses .....???

**Comment by m-r-davari** [comment]
**Hi,**

For now, if your 3D model supports different **embedded textures/variants**, you can easily switch between them. For example, if you have a 3D character model with different embedded variants for the clothes, you can select between the variants. You can check the example to see how it works.

But the feature you mentioned is a great improvement. I will check to find a way to implement it if it's possible. **Thanks**

**Comment by illusionGeorge** [comment]
ok.Thanks
