### ISSUE TITLE
.glb in build version

### ISSUE THREAD

**Issue by aes1998** [m-r-davari/flutter_3d_controller#32]
Hi

I run the project in debug mode without any issue.

When I build the project as apk, all .glb objects are not showing.

Is there any way to fix it?

**Comment by m-r-davari** [comment]
Hi,

Did you add the clear text permission to the android manifest?

`android:usesCleartextTraffic="true"`

If not please review the readme and installation guide

**Comment by aes1998** [comment]
Yes, I added it to android/app/src/main/AndroidManifest.xml.

**Comment by m-r-davari** [comment]
You need to add this permission into your android manifest too,

`<uses-permission android:name="android.permission.INTERNET"/>`

I forgot to add it in readme and example
Thanks for reporting, I will update readme in next version 2.0.1

**Comment by aes1998** [comment]
Thank you so much for your help and efforts. It's work.
