### ISSUE TITLE
Last release doesn't work in web version

### ISSUE THREAD

**Issue by shegal** [m-r-davari/flutter_3d_controller#34]
1) if target device is chrome browser: glb files don't load witn new Flutter3DViewer (model isn't displayed, any attempts of calling set texture or animation lead to error "Flutter3DControllerLoadingException: The 3D model is not loaded yet or is still loading.")
2) if target device is android emulator: glb files are loaded but slowly (approximately twice longer comparing to previous release), when it is loaded  - starting animation is not played until first update, setting texture/animation not always work correctly

**Comment by m-r-davari** [comment]
Hi,
Latest version works fine on web even with multiple model, you need to **update your index.html head tag** 

`<head>
  
    <script type="module" src="./assets/packages/flutter_3d_controller/assets/model_viewer.min.js" defer></script>
</head>`

**Screenshot :** 
<img width="499" alt="Screenshot 2024-10-09 at 16 53 57" src="https://github.com/user-attachments/assets/53291729-c00d-41c5-8fd1-6278123225e1">

**Comment by shegal** [comment]
Yes, it helped! Thank you and sorry for false alarm)

**Comment by shegal** [comment]
Hm, how did you manage to load two different models in one viewer? :)

**Comment by m-r-davari** [comment]
Your welcome, please don't forget to support me with pubDev like and GitHub star, 
You can check the example for loading multiple models
