### ISSUE TITLE
Cannot create second 3d controller - it just duplicates first one

### ISSUE THREAD

**Issue by shegal** [m-r-davari/flutter_3d_controller#36]
I have viewer  with controller on the main screen and they work perfectly fine. But if I try to create second viewer in modal window (so first viewer still present on screen) with another controller it seems like both controllers are the same and control viewer on the main screen.

**Comment by m-r-davari** [comment]
You need to create separate controller for each model viewer, for example if you have 3 model viewer then you need to create 3 controller

**Comment by shegal** [comment]
Of course I do create separate controllers (can provide you with code example if it is necessary). Seems like there is something underhood the controller with shared state or something like that.

**Comment by m-r-davari** [comment]
Ok then send your code for further progress, because I can't see the issue you mentioned in my case

**Comment by m-r-davari** [comment]
Hi again,
I checked your code, there is a bug with controller on web platworm, I did not see the bugs because I checked mobile platforms.
Thanks a lot for reporting this issue and helping me improving this package.
I will fix this issue in next version as soon as possible

**Comment by m-r-davari** [comment]
I have fixed this issue in v2.0.2. Please check out the latest version.
[](https://pub.dev/packages/flutter_3d_controller)

Let me know if you find any other issues.

**Comment by shegal** [comment]
Yes, now it is working! Thanks a lot!
