### ISSUE TITLE
Build failed with an exception with latest flutter version.

### ISSUE THREAD

**Issue by sAw-hTet-nAing** [m-r-davari/flutter_3d_controller#38]
I'm facing this issue with latest flutter version  3.24.3.

I created fresh project to test this package, but I'm facing this issue.I researched for solution and found out  that this issue is related to JDK compatibility, as other users suggest downgrading to JDK 11 or 17.
Due to work requirements, I need to retain JDK 22, and switching to an older JDK version is not feasible.
It would be ideal if there were a solution or workaround compatible with JDK 22.

My `flutter --version`

`Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (6 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3`

My IDE 
Android Studio - Lady Bug

`FAILURE: Build failed with an exception.

 What went wrong:
Execution failed for task ':webview_flutter_android:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':webview_flutter_android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/saw/Library/Android/sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/jlink with arguments {--module-path /Users/saw/.gradle/caches/transforms-3/d9e926982c2c139ff9125eb7b6be4144/transformed/output/temp/jmod --add-modules java.base --output /Users/saw/.gradle/caches/transforms-3/d9e926982c2c139ff9125eb7b6be4144/transformed/output/jdkImage --disable-plugin system-modules}`

**Comment by m-r-davari** [comment]
It must be related to the version of [webView](https://pub.dev/packages/webview_flutter) package that I used in my package, if you are in hurry you can easily change it to highest version to fix issue,
I will check it as soon as possible

**Comment by sAw-hTet-nAing** [comment]
@m-r-davari 
Sorry for late reply .It turns out the issue wasn't related to any package or third-party library after all. The problem was actually with my Java version. I was using Java 22, which isn't compatible with Flutter, so I downgraded to Java 17. After updating the JDK directory in the Flutter configuration, everything is now working perfectly.So I will close this issue.
