### ISSUE TITLE
Clicking on 3D Models and Feature to Zoom In on the Clicked Model Part

### ISSUE THREAD

**Issue by orhanboz** [m-r-davari/flutter_3d_controller#4]
First of all, congratulations on creating a successful library. Upon inspecting the library, I noticed that it only covers basic features such as viewing, animation, etc. However, I would like to request the addition of features like clicking on a multi-part object in OBJ format and displaying a selected effect when clicked. Thank you.

**Comment by m-r-davari** [comment]
Thank you, this is good idea i will put it on R&D list for next versions.
