### ISSUE TITLE
View Application Directory Models

### ISSUE THREAD

**Issue by zynzszyn521** [m-r-davari/flutter_3d_controller#7]
I want to download models from the network and preview them after saving them in the application's directory. Is this approach feasible? I noticed that in your example, you passed a static file path; can it instead reference files within the application's directory?

**Comment by zynzszyn521** [comment]
> this package support loading models from URL, just pass the URL instead of static path.

but my models in ftp server,there have no nginx or any other proxy site, so i must download it and save to local directory ,can you help me

**Comment by zynzszyn521** [comment]
> 在这种情况下，您有两种选择，首先下载模型并从中创建文件，然后采用其临时路径。其次下载模型并将其保存到本地存储，然后获取保存模型的路径并将其传递给包，您的用例需要的不仅仅是模型查看器库，例如您可以使用 [Dio](https://pub.dev/packages/dio) 包来下载您的模型。

my code it's below ,but it's not working
````
Directory appDocDir = await getApplicationDocumentsDirectory();
String  filePath = '${appDocDir.path}/local.glb';
Flutter3DViewer(
        controller: controller.three3Dcontroller,
        src: filePath,
         )
````

**Comment by m-r-davari** [comment]
As your issue is not about the package and its about your use case maybe it needs more research, I have no more Idea right now, if you found way to solve share it please share, thanks.
