### ISSUE TITLE
Dynamically add textures from a path

### ISSUE THREAD

**Issue by nirmal-kc** [m-r-davari/flutter_3d_controller#8]
I have a simple sofa with white background in my .glb file. I want to change the fabric based on the option selected by the user, I have url's for the fabric images. Is this possible?

**Comment by nirmal-neogrc** [comment]
Also, can you explain how the textures are loaded in your example? I believe the samples are created using Babylon. Correct me if wrong.

**Comment by m-r-davari** [comment]
its better to use embedded texture models, and for dynamic texture/variant your model must support that... if you are familiar with 3d models you can check [this model ](https://github.com/KhronosGroup/glTF-Sample-Models/blob/main/2.0/SheenChair/glTF-Binary/SheenChair.glb)to see how to create models with multiple variants.

**Comment by nirmal-kc** [comment]
But, does this package support dynamic texture/variant option? My model does support it, but is there an API I can refer to? To fetch and load dynamic materials?

**Comment by TouSC** [comment]
have you figure out how to do it?
