### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by jadantoun0** [m-r-davari/flutter_3d_controller#9]
When I try to load a glb object in iOS and invoke this method:

animations = await _controller.getAvailableAnimations();

I get the following error:

Exception has occurred.
FormatException (FormatException: Unexpected character (at character 1)
(
^
)

Any idea how I can solve this issue?

Note that its working well on Android.

**Comment by m-r-davari** [comment]
Do you have same problem with example models too?
It may be a bug inside of the package.
This error will occurs when the package tries to fetch animation names from the model. I will take look at it later, but if you're in a hurry, you can fix it and create a pull request.
Thank you for reporting this bug.

Note: You can also try another model; perhaps your model's animation names contain some unusual characters.

**Comment by m-r-davari** [comment]
Fixed on version 1.3.1 ✅
